version: "3.7"

services:
  server:
    build:
      context: ./
    container_name: starter
    image: starter
    ports:
      - "3900:3900"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: starter_db
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always
    networks:
      - backend
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mvertes/alpine-mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
